### ISSUE TITLE
Is Big Huge Thesaurus the best tool for this?

### ISSUE THREAD

**Issue by bigbeno37** [eightnoteight/x-thesaurus#1]
I mean, alternatively, you could use regex expressions to get the contents of 
http://dictionary . reference . com / browse / <word> without needing an account or API key. 

(Sorry for the spaces; I needed to remove the auto hypertexting)

**Comment by zsrinivas** [comment]
I'm extremely sorry this very very late reply, somehow i skipped this issue from my notifications.
at that time i was just trying to learn about REST API apps. and also I did some googling and found out that Big Huge Thesaurus is best at that time.
you should also remember that if those websites UI changes, the app becomes useless. and that is why is better to use API.
